version: 2.1

orbs:
  ggshield: gitguardian/ggshield@1.1.4
  snyk: snyk/snyk@1.4.0

workflows:
  build_and_deploy:
    jobs:
      - ggshield/scan:
          name: secrets_detection
          revision: $CIRCLE_SHA1
          context:
            - dobra
      - static_analysis:
          context:
            - dobra
          matrix:
            parameters:
              target-file:
                - inventory/pom.xml
                - cart/pom.xml
                - wishlist/pom.xml
          # requires:
          #   - secrets_detection
      - build:
          requires:
            - static_analysis
      - test

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Cart JAR
          command: |
            cd cart && mvn -U clean package && cd ..
      - store_artifacts:
          path: cart/target
      - run:
          name: Build Inventory JAR
          command: |
            cd inventory && mvn -U clean package && cd ..
      - store_artifacts:
          path: inventory/target
  static_analysis:
    parameters:
      target-file:
        type: string
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - snyk/scan:
          severity-threshold: critical
          target-file: << parameters.target-file >>
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            mvn test