version: 2.1

orbs:
  snyk: snyk/snyk@1.4.0

workflows:
  build_and_deploy:
    jobs:
      - sast
      - build:
          requires:
            - sast

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build JAR files
          command: |
            cd cart
            mvn -U clean package
      - store_artifacts:
          path: cart/target
  sast:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - snyk/scan:
          severity-threshold: high