version: 2.1

orbs:
  ggshield: gitguardian/ggshield@1.1.4
  snyk: snyk/snyk@1.4.0

workflows:
  build_and_deploy:
    jobs:
      - ggshield/scan:
          name: secrets_detection
          revision: $CIRCLE_SHA1
          context:
            - dobra
      - static_analysis:
          name: sast-<< matrix.service >>
          context:
            - dobra
          matrix:
            parameters:
              service:
                - inventory
                - cart
                - wishlist
          requires:
            - secrets_detection
      - test:
          name: test-<< matrix.service >>
          matrix:
            parameters:
              service:
                - inventory
                - cart
                - wishlist
          requires:
            - sast-<< matrix.service >>
      - build:
          name: build-<< matrix.service >>
          matrix:
            parameters:
              service:
                - inventory
                - cart
                - wishlist
          requires:
            - test-<< matrix.service >>

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Cart JAR
          command: |
            cd cart && mvn -U clean package && cd ..
      - store_artifacts:
          path: cart/target
      - run:
          name: Build Inventory JAR
          command: |
            cd inventory && mvn -U clean package && cd ..
      - store_artifacts:
          path: inventory/target
  static_analysis:
    parameters:
      service:
        type: string
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - snyk/scan:
          severity-threshold: critical
          target-file: << parameters.service >>/pom.xml
  test:
    parameters:
      service:
        type: string
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            cd << parameters.service >>
            mvn test